You'll use the numpy library throughout.
1. In python, create a function grandmatrix(n, m = 10) that takes integers n and m, and returns an nxn numpy array with each element a random integer in the range -m to m. Do this from scratch. (grandmatrix means griffin rand matrix, not 'really epic matrix')
2. Now do the same thing using numpy.randint.
3. Create a function gmatmult that takes two numpy arrays a and b, checks that they are compatible square matrices, raising an error if not, and returns their matrix product as a numpy array. For this you'll need to use loops.
4. Test this on a few 2x2 matrices created by your grandmatrix function to make sure it's working. You can use the numpy eye() function to create an identity matrix to test it for multiplying the identity too.
5. Now create a function cmatmult that does the same thing, but this time you're allowed to use the numpy matmult or @ operator. Do gmatmult and cmatmult give the same answers? Try them with a few random 6x6 matrices.
6. What would you think the advantage might be of using the built in functions in cmatmult vs your own loops in gmatmult?
7. Now test the performance (that means speed) of the gmatmult vs cmatmult. You can use the %%timeit function for this. Try it on some much larger matrices and see how the performance compares. What's the biggest size matrix you might conveniently multiply with your own version vs the 'native' version?

In [ ]:
# this is thing

1. In python, create a function grandmatrix(n, m = 10) that takes integers n and m, and returns an nxn numpy array with each element a random integer in the range -m to m. Do this from scratch. (grandmatrix means griffin rand matrix, not 'really epic matrix')

In [110]:
# 1.

import random
import numpy as np

def g_rand_matrix(n, m = 100):
    matrix = []
    for i in range(n):
        row = []
        for j in range(n):
            row.append(random.randint(-m, m))
        matrix.append(row)
    return np.array(matrix)

In [111]:
print(g_rand_matrix(6))

[[-89  83 -22  -9 -49  59]
 [ 70  58  43   3  28  33]
 [-31  -3 -45  -7 -26 -40]
 [-56 -62  96  87  27 -77]
 [ 97   4 -36 -39  30  85]
 [ 50   0  45 -98  32 -56]]


2. Now do the same thing using numpy.randint.

In [108]:
# 2.

import numpy as np

def numpy_rand_matrix(n, m=100):
    return np.random.randint(-m, m + 1, size=(n, n))

In [109]:
print(numpy_rand_matrix(5))

[[ -6  22 -65  72  31]
 [ 26 -58 -58 -39 -32]
 [ 92  86   5  83   5]
 [-30  86  26  11 -10]
 [-78 -38  39  77 -84]]


3. Create a function gmatmult that takes two numpy arrays a and b, checks that they are compatible square matrices, raising an error if not, and returns their matrix product as a numpy array. For this you'll need to use loops.

In [27]:
# 3.
def g_mat_mult(a, b):

    if a.shape[0] != a.shape[1] or b.shape[0] != b.shape[1]:
        raise ValueError('not square matricies')

    if a.shape[0] != b.shape[1]:
        raise ValueError('not compatible matricies ')
    
    n = a.shape[0]
    product = []
    
    for i in range(n):
        row = []
        for j in range(n):
            row.append(0)
            for k in range(n):
                row[j] += a[i][k] * b[k][j]
        product.append(row)
    
    return np.array(product, dtype=float)


4. Test this on a few 2x2 matrices created by your grandmatrix function to make sure it's working. You can use the numpy eye() function to create an identity matrix to test it for multiplying the identity too.

In [31]:
# 4.
print(g_mat_mult(np.eye(2), np.array([[2,3],[5,4]])))

print(g_mat_mult(np.array([[7,4],[0,3]]), np.array([[2,3],[5,4]])))

[[2. 3.]
 [5. 4.]]
[[34. 37.]
 [15. 12.]]


5. Now create a function cmatmult that does the same thing, but this time you're allowed to use the numpy matmult or @ operator. Do gmatmult and cmatmult give the same answers? Try them with a few random 6x6 matrices.

In [37]:
# 5.
def c_mat_mult(a, b):
    
    if a.shape[0] != a.shape[1] or b.shape[0] != b.shape[1]:
        raise ValueError('not square matricies')

    if a.shape[0] != b.shape[1]:
        raise ValueError('not compatible matricies ')
    
    return np.array(np.matmul(a, b), dtype=float)

In [40]:
print(c_mat_mult(np.array([[7,4],[0,3]]), np.array([[2,3],[5,4]])))
print(g_mat_mult(np.array([[7,4],[0,3]]), np.array([[2,3],[5,4]])))

[[34. 37.]
 [15. 12.]]
[[34. 37.]
 [15. 12.]]


In [112]:
x = g_rand_matrix(6)
y = g_rand_matrix(6)

print(g_mat_mult(x, y))
print(c_mat_mult(x, y))

[[ 5957.  4039.  1546.  6384. -2103.  3536.]
 [ 3586.  4716.   117.  3234. -7297. -7346.]
 [ 4547. 12243.  1630.  4054.  3246. -3562.]
 [-6248.  3498.  4937. -3663. 11069. -7919.]
 [  896.  6014. -1884. -6580. -2469. -9088.]
 [-5707. -6226.  9388.  5842.  5267. -3001.]]
[[ 5957.  4039.  1546.  6384. -2103.  3536.]
 [ 3586.  4716.   117.  3234. -7297. -7346.]
 [ 4547. 12243.  1630.  4054.  3246. -3562.]
 [-6248.  3498.  4937. -3663. 11069. -7919.]
 [  896.  6014. -1884. -6580. -2469. -9088.]
 [-5707. -6226.  9388.  5842.  5267. -3001.]]


6. What would you think the advantage might be of using the built in functions in cmatmult vs your own loops in gmatmult?

because time

7. Now test the performance (that means speed) of the gmatmult vs cmatmult. You can use the %%timeit function for this. Try it on some much larger matrices and see how the performance compares. What's the biggest size matrix you might conveniently multiply with your own version vs the 'native' version?

In [113]:
# 7. 
import timeit


# timing
print(timeit.timeit('g_mat_mult(x, y)', globals=globals(), number=10000))
print(timeit.timeit('c_mat_mult(x, y)', globals=globals(), number=10000))

# c_mat_mult can do 100000 no problem, but g is too slow

1.130906005972065
0.023468256986234337


In [122]:
xx = g_rand_matrix(100)
yy = g_rand_matrix(100)

In [116]:
# BETTER WAY alegidly

In [123]:
%%timeit
c_mat_mult(xx, yy)

546 μs ± 3.17 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [124]:
%%timeit
g_mat_mult(xx, yy)

437 ms ± 9.05 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [125]:
# c 1000 times faster

In [74]:
# testing timeit()
import timeit
import random
import_module = "import random"

def test(): 
    return random.randint(10, 100)


print(timeit.timeit('test()', globals=globals(), number=1))

5.999987479299307e-06


In [ ]:
# einstein stuff

In [127]:
def e_mat_mult(a, b):
    return np.array(np.einsum('ik, kj -> ij', a, b), dtype=float)

In [128]:
print(c_mat_mult(np.array([[7,4],[0,3]]), np.array([[2,3],[5,4]])))
print(e_mat_mult(np.array([[7,4],[0,3]]), np.array([[2,3],[5,4]])))

[[34. 37.]
 [15. 12.]]
[[34. 37.]
 [15. 12.]]


In [129]:
print(g_mat_mult(xx, yy))
print(e_mat_mult(xx, yy))

[[-13236. -74116. -17269. ...   -288.  42104. -11397.]
 [ 20838.   -418.   5482. ...  42402.  15548.  19697.]
 [  7168. -59418. -37573. ...  14677. -37760.  13839.]
 ...
 [ 17604.  34902.   5273. ...  -2112. -45622. -99782.]
 [ -5866.  23255. -12846. ...   8092.  43521. -29477.]
 [ -7060.  67394. -42804. ...  16230.  61013.  27971.]]
[[-13236. -74116. -17269. ...   -288.  42104. -11397.]
 [ 20838.   -418.   5482. ...  42402.  15548.  19697.]
 [  7168. -59418. -37573. ...  14677. -37760.  13839.]
 ...
 [ 17604.  34902.   5273. ...  -2112. -45622. -99782.]
 [ -5866.  23255. -12846. ...   8092.  43521. -29477.]
 [ -7060.  67394. -42804. ...  16230.  61013.  27971.]]


In [102]:
import timeit

# initialising matrices
x = np.random.randint(0, 100, size=(20, 20))
y = np.random.randint(0, 100, size=(20, 20))

numtimes = 10 ** 5

# timing
print(timeit.timeit('c_mat_mult(x, y)', globals=globals(), number=numtimes))
print(timeit.timeit('e_mat_mult(x, y)', globals=globals(), number=numtimes))

0.7044883850030601
0.7884677900001407


In [105]:
import timeit

# initialising matrices
x = np.array([[1,2,4,3,5,6],[4,5,3,6,7,8],[2,3,5,1,2,3],[9,0,0,8,7,8],[5,6,4,3,7,8],[2,1,2,1,2,1]])
y = np.array([[3,4,3,4,3,4],[3,6,7,8,5,6],[5,4,7,6,8,3],[4,0,0,9,0,9],[4,1,1,2,1,2],[4,7,6,5,4,3]])

numtimes = 10 ** 6

# timing
print(timeit.timeit('c_mat_mult(x, y)', globals=globals(), number=numtimes))
print(timeit.timeit('e_mat_mult(x, y)', globals=globals(), number=numtimes))


2.327162633999251
2.969280399964191


In [ ]:
# BETTER WAY

In [134]:
xxx = g_rand_matrix(1000)
yyy = g_rand_matrix(1000)

In [135]:
%%timeit
c_mat_mult(xxx, yyy)

582 ms ± 7.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [136]:
%%timeit
e_mat_mult(xxx, yyy)

466 ms ± 2.58 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Einstein summation convention seems to be slightly fster than direct numpy matmul