You'll use the numpy library throughout.
1. In python, create a function grandmatrix(n, m = 10) that takes integers n and m, and returns an nxn numpy array with each element a random integer in the range -m to m. Do this from scratch. (grandmatrix means griffin rand matrix, not 'really epic matrix')
2. Now do the same thing using numpy.randint.
3. Create a function gmatmult that takes two numpy arrays a and b, checks that they are compatible square matrices, raising an error if not, and returns their matrix product as a numpy array. For this you'll need to use loops.
4. Test this on a few 2x2 matrices created by your grandmatrix function to make sure it's working. You can use the numpy eye() function to create an identity matrix to test it for multiplying the identity too.
5. Now create a function cmatmult that does the same thing, but this time you're allowed to use the numpy matmult or @ operator. Do gmatmult and cmatmult give the same answers? Try them with a few random 6x6 matrices.
6. What would you think the advantage might be of using the built in functions in cmatmult vs your own loops in gmatmult?
7. Now test the performance (that means speed) of the gmatmult vs cmatmult. You can use the %%timeit function for this. Try it on some much larger matrices and see how the performance compares. What's the biggest size matrix you might conveniently multiply with your own version vs the 'native' version?

In [ ]:
# this is thing

1. In python, create a function grandmatrix(n, m = 10) that takes integers n and m, and returns an nxn numpy array with each element a random integer in the range -m to m. Do this from scratch. (grandmatrix means griffin rand matrix, not 'really epic matrix')

In [ ]:
# 1.

import random

def g_rand_matrix(n, m = 10):
    matrix = []
    for i in range(n):
        row = []
        for j in range(n):
            row.append(random.randint(-m, m))
        matrix.append(row)
    return matrix

2. Now do the same thing using numpy.randint.

In [11]:
# 2.

import numpy as np

def numpy_rand_matrix(n, m=10):
    return np.random.randint(-m, m + 1, size=(n, n))

3. Create a function gmatmult that takes two numpy arrays a and b, checks that they are compatible square matrices, raising an error if not, and returns their matrix product as a numpy array. For this you'll need to use loops.

In [27]:
# 3.
def g_mat_mult(a, b):

    if a.shape[0] != a.shape[1] or b.shape[0] != b.shape[1]:
        raise ValueError('not square matricies')

    if a.shape[0] != b.shape[1]:
        raise ValueError('not compatible matricies ')
    
    n = a.shape[0]
    product = []
    
    for i in range(n):
        row = []
        for j in range(n):
            row.append(0)
            for k in range(n):
                row[j] += a[i][k] * b[k][j]
        product.append(row)
    
    return np.array(product, dtype=float)


4. Test this on a few 2x2 matrices created by your grandmatrix function to make sure it's working. You can use the numpy eye() function to create an identity matrix to test it for multiplying the identity too.

In [31]:
# 4.
print(g_mat_mult(np.eye(2), np.array([[2,3],[5,4]])))

print(g_mat_mult(np.array([[7,4],[0,3]]), np.array([[2,3],[5,4]])))

[[2. 3.]
 [5. 4.]]
[[34. 37.]
 [15. 12.]]


5. Now create a function cmatmult that does the same thing, but this time you're allowed to use the numpy matmult or @ operator. Do gmatmult and cmatmult give the same answers? Try them with a few random 6x6 matrices.

In [37]:
# 5.
def c_mat_mult(a, b):
    
    if a.shape[0] != a.shape[1] or b.shape[0] != b.shape[1]:
        raise ValueError('not square matricies')

    if a.shape[0] != b.shape[1]:
        raise ValueError('not compatible matricies ')
    
    return np.array(np.matmul(a, b), dtype=float)

In [40]:
print(c_mat_mult(np.array([[7,4],[0,3]]), np.array([[2,3],[5,4]])))
print(g_mat_mult(np.array([[7,4],[0,3]]), np.array([[2,3],[5,4]])))

[[34. 37.]
 [15. 12.]]
[[34. 37.]
 [15. 12.]]


In [62]:
x = np.array([[1,2,4,3,5,6],[4,5,3,6,7,8],[2,3,5,1,2,3],[9,0,0,8,7,8],[5,6,4,3,7,8],[2,1,2,1,2,1]])
y = np.array([[3,4,3,4,3,4],[3,6,7,8,5,6],[5,4,7,6,8,3],[4,0,0,9,0,9],[4,1,1,2,1,2],[4,7,6,5,4,3]])

print(g_mat_mult(x, y))
print(c_mat_mult(x, y))

[[ 85.  79.  86. 111.  74.  83.]
 [126. 121. 123. 182. 100. 147.]
 [ 64.  69.  82.  90.  75.  63.]
 [119.  99.  82. 162.  66. 146.]
 [125. 135. 140. 173. 116. 133.]
 [ 35.  31.  35.  46.  33.  36.]]
[[ 85.  79.  86. 111.  74.  83.]
 [126. 121. 123. 182. 100. 147.]
 [ 64.  69.  82.  90.  75.  63.]
 [119.  99.  82. 162.  66. 146.]
 [125. 135. 140. 173. 116. 133.]
 [ 35.  31.  35.  46.  33.  36.]]


6. What would you think the advantage might be of using the built in functions in cmatmult vs your own loops in gmatmult?

because time

7. Now test the performance (that means speed) of the gmatmult vs cmatmult. You can use the %%timeit function for this. Try it on some much larger matrices and see how the performance compares. What's the biggest size matrix you might conveniently multiply with your own version vs the 'native' version?

In [84]:
# 7. 
import timeit

# initialising matrices
x = np.array([[1,2,4,3,5,6],[4,5,3,6,7,8],[2,3,5,1,2,3],[9,0,0,8,7,8],[5,6,4,3,7,8],[2,1,2,1,2,1]])
y = np.array([[3,4,3,4,3,4],[3,6,7,8,5,6],[5,4,7,6,8,3],[4,0,0,9,0,9],[4,1,1,2,1,2],[4,7,6,5,4,3]])

# timing
print(timeit.timeit('g_mat_mult(x, y)', globals=globals(), number=10000))
print(timeit.timeit('c_mat_mult(x, y)', globals=globals(), number=10000))

# c_mat_mult can do 100000 no problem, but g is too slow

1.124857268994674
0.023158397001679987


In [74]:
# testing timeit()
import timeit
import random
import_module = "import random"

def test(): 
    return random.randint(10, 100)


print(timeit.timeit('test()', globals=globals(), number=1))

5.999987479299307e-06
